# Generated by Django 6.0 on 2026-01-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('boards_app', '0003_alter_board_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('review', 'Review'), ('done', 'Done'), ('to-do', 'To Do'), ('in-progress', 'In Progress')], default='to-do', max_length=11)),
                ('due_date', models.DateField()),
                ('asignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='auth_app.userprofile')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards_app.board')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_reviewing', to='auth_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.userprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task')),
            ],
        ),
    ]
