# Generated by Django 6.0 on 2026-01-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_alter_comment_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asignee',
            new_name='assignee',
        ),
    ]
