# Generated by Django 6.0 on 2026-01-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('tasks_app', '0004_rename_asignee_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.userprofile'),
            preserve_default=False,
        ),
    ]
