# Generated by Django 6.0 on 2026-01-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_alter_board_members'),
        ('tasks_app', '0005_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='boards_app.board'),
        ),
    ]
