# Generated by Django 6.0 on 2026-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('boards_app', '0002_alter_board_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='board_members', to='auth_app.userprofile'),
        ),
    ]
